
---
- name: Add Docker Group
  group: name=docker state=present

- name: Add ubuntu to Docker group
  user: name=ubuntu state=present groups="docker"

- name: install virtualenv
  apt: name=virtualenvwrapper state=present

- name: Install docker-py
  pip: "name=docker-py virtualenv={{ charmdir/.venv }}"
