---
- name: remove lxc-docker
  shell: apt-get remove -y lxc-docker
  when: latest_installed

- name: Remove Docker Group
  group: name=docker state=absent

- debug: msg="Install docker from universe"

- name: Install required packages.
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=6000
  with_items:
    - docker.io
  when: latest == false

- name: Add ubuntu to Docker group
  user: name=ubuntu state=present groups="docker"

